import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const tokensFile = path.join(root, 'packages/design-tokens/tokens.json');
export const cssFile = path.join(root, 'web/src/app/design-tokens.css');
export const kotlinFile = path.join(root, 'android/app/src/main/java/com/community/platform/DesignTokens.kt');
export const globalsFile = path.join(root, 'web/src/app/globals.css');
export const themeFile = path.join(root, 'android/app/src/main/java/com/community/platform/CommunityTheme.kt');
const notice = 'Generated by scripts/design-tokens.mjs from packages/design-tokens/tokens.json. Do not edit; run npm run tokens.';
const sizes = ['spacingUnit', 'controlRadius', 'dialogRadius', 'minimumWebTarget', 'minimumAndroidTarget'];

// Text needs 4.5:1; a border that shows where a control is needs 3:1.
export const contrastPairs = [
  ['ink', 'background', 4.5], ['ink', 'surface', 4.5], ['ink', 'primarySurface', 4.5],
  ['ink', 'dangerSurface', 4.5], ['ink', 'warningSurface', 4.5],
  ['muted', 'background', 4.5], ['muted', 'surface', 4.5], ['placeholder', 'surface', 4.5],
  ['primary', 'background', 4.5], ['primary', 'surface', 4.5], ['primary', 'primarySurface', 4.5],
  ['surface', 'primary', 4.5], ['surface', 'primaryHover', 4.5], ['surface', 'accent', 4.5],
  ['accent', 'background', 4.5], ['accent', 'surface', 4.5], ['accent', 'warningSurface', 4.5],
  ['danger', 'background', 4.5], ['danger', 'surface', 4.5], ['danger', 'dangerSurface', 4.5],
  ['controlBorder', 'background', 3], ['controlBorder', 'surface', 3],
];

// Feature stylesheets moved to tokens; any other stylesheet joins this list once it uses only token variables.
export const tokenStylesheets = [
  'care/care.module.css', 'events/events.module.css', 'community/community.module.css',
  'messaging/messages.module.css', 'planning/tasks.module.css', 'planning/checklist.module.css',
  'platform/navigation.module.css', 'platform/home.module.css',
].map(file => path.join(root, 'web/src/features', file));
// Android screens whose corners and target heights come from DesignTokens; a row taller than the minimum target, such as 56 dp, may stay a number.
export const tokenScreens = [
  'identity/IdentityScreen.kt', 'planning/TaskScreen.kt', 'messaging/MessagingScreen.kt',
  'community/CommunityScreen.kt', 'care/CareScreen.kt', 'events/EventsScreen.kt',
].map(file => path.join(root, 'android/app/src/main/java/com/community/platform/feature', file));
const olderNames = ['ink', 'muted', 'green', 'green-hover', 'green-soft', 'canvas', 'line', 'white', 'accent', 'danger', 'radius'];

export const read = file => readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
const kebab = name => name.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`);
const pascal = name => name[0].toUpperCase() + name.slice(1);

export function checkTokens(tokens) {
  const problems = [];
  if (tokens?.version !== 1) problems.push('version must be 1');
  if (typeof tokens?.font?.family !== 'string' || !/^[A-Za-z0-9 ]{1,60}$/.test(tokens.font.family)) problems.push('font.family must be a plain font name');
  if (tokens?.font?.letterSpacing !== 0) problems.push('font.letterSpacing must be 0');
  const colors = Object.entries(tokens?.color ?? {});
  if (colors.length === 0) problems.push('color must name at least one colour');
  for (const [name, value] of colors) {
    if (!/^[a-z][A-Za-z0-9]{0,39}$/.test(name)) problems.push(`colour name ${name} must be camelCase`);
    if (typeof value !== 'string' || !/^#[0-9a-f]{6}$/.test(value)) problems.push(`colour ${name} must be #rrggbb in lower case`);
  }
  for (const key of sizes) {
    if (!Number.isInteger(tokens?.[key]) || tokens[key] < 1 || tokens[key] > 96) problems.push(`${key} must be a whole number from 1 to 96`);
  }
  const needed = new Set(contrastPairs.flatMap(([foreground, background]) => [foreground, background]));
  for (const name of needed) if (!(name in (tokens?.color ?? {}))) problems.push(`colour ${name} is needed for a contrast check`);
  return problems;
}

export function loadTokens(file = tokensFile) {
  const tokens = JSON.parse(readFileSync(file, 'utf8'));
  const problems = checkTokens(tokens);
  if (problems.length) throw new Error(`${path.relative(root, file)}: ${problems.join('; ')}`);
  return tokens;
}

export function renderCss(tokens) {
  return [
    `/* ${notice} */`,
    ':root {',
    ...Object.entries(tokens.color).map(([name, value]) => `  --color-${kebab(name)}: ${value};`),
    `  --font-family: "${tokens.font.family}";`,
    `  --space-unit: ${tokens.spacingUnit}px;`,
    `  --radius-control: ${tokens.controlRadius}px;`,
    `  --radius-dialog: ${tokens.dialogRadius}px;`,
    `  --target-minimum: ${tokens.minimumWebTarget}px;`,
    '}',
    '',
  ].join('\n');
}

export function renderKotlin(tokens) {
  return [
    `// ${notice}`,
    'package com.community.platform',
    '',
    'import androidx.compose.ui.graphics.Color',
    'import androidx.compose.ui.unit.dp',
    'import androidx.compose.ui.unit.sp',
    '',
    'object DesignTokens {',
    ...Object.entries(tokens.color).map(([name, value]) => `    val ${pascal(name)} = Color(0xFF${value.slice(1).toUpperCase()})`),
    `    val LetterSpacing = ${tokens.font.letterSpacing}.sp`,
    `    val SpaceUnit = ${tokens.spacingUnit}.dp`,
    `    val ControlRadius = ${tokens.controlRadius}.dp`,
    `    val DialogRadius = ${tokens.dialogRadius}.dp`,
    `    val MinimumTarget = ${tokens.minimumAndroidTarget}.dp`,
    '}',
    '',
  ].join('\n');
}

function luminance(hex) {
  const channel = index => {
    const value = parseInt(hex.slice(1 + index * 2, 3 + index * 2), 16) / 255;
    return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * channel(0) + 0.7152 * channel(1) + 0.0722 * channel(2);
}

export function contrastRatio(foreground, background) {
  const [light, dark] = [luminance(foreground), luminance(background)].sort((a, b) => b - a);
  return (light + 0.05) / (dark + 0.05);
}

export function contrastFailures(tokens) {
  return contrastPairs
    .map(([foreground, background, minimum]) => ({ foreground, background, minimum, ratio: contrastRatio(tokens.color[foreground], tokens.color[background]) }))
    .filter(pair => pair.ratio < pair.minimum)
    .map(pair => `${pair.foreground} on ${pair.background}: ${pair.ratio.toFixed(2)}:1, needs ${pair.minimum}:1`);
}

export function findHandCopies(tokens, texts = { [globalsFile]: read(globalsFile), [themeFile]: read(themeFile) }) {
  const found = [];
  for (const [file, text] of Object.entries(texts)) {
    const where = path.relative(root, file).replaceAll('\\', '/');
    const kotlin = file.endsWith('.kt');
    for (const [name, value] of Object.entries(tokens.color)) {
      const hex = value.slice(1);
      const short = /^(.)\1(.)\2(.)\3$/.test(hex) ? `${hex[0]}${hex[2]}${hex[4]}` : null;
      const patterns = kotlin
        ? [new RegExp(`0x[0-9a-f]{2}${hex}(?![0-9a-f])`, 'i')]
        : [new RegExp(`#${hex}(?![0-9a-f])`, 'i'), ...(short ? [new RegExp(`#${short}(?![0-9a-f])`, 'i')] : [])];
      if (value === '#ffffff') patterns.push(kotlin ? /Color\.White\b/ : /(?<![\w-])white(?![\w-])/i);
      if (patterns.some(pattern => pattern.test(text))) found.push(`${where}: colour ${name} (${value}) is typed by hand`);
    }
    if (!kotlin) {
      const family = `"${tokens.font.family}"`;
      if (!text.includes(`@font-face{font-family:${family};`)) found.push(`${where}: the @font-face rule must name ${family}`);
      if (text.split(family).length !== 2) found.push(`${where}: ${family} may appear only in the @font-face rule`);
      if (!text.startsWith('@import "./design-tokens.css";')) found.push(`${where}: must start by importing design-tokens.css`);
    }
  }
  return found;
}

export function findStyleViolations(texts = Object.fromEntries(tokenStylesheets.map(file => [file, read(file)]))) {
  const found = [];
  for (const [file, text] of Object.entries(texts)) {
    const where = path.relative(root, file).replaceAll('\\', '/');
    const css = text.replace(/\/\*[\s\S]*?\*\//g, '');
    const report = (problem, values) => { for (const value of new Set(values)) found.push(`${where}: ${problem} ${value}`); };
    report('typed colour', css.match(/#[0-9a-f]{3,8}\b/gi) ?? []);
    report('colour function', css.match(/\b(?:rgba?|hsla?)\(/gi) ?? []);
    report('named colour', css.match(/(?<![\w-])(?:white|black)(?![\w-])/gi) ?? []);
    report('older variable', (css.match(/var\(--[a-z-]+/g) ?? []).filter(name => olderNames.includes(name.slice(6))).map(name => `${name})`));
    report('fallback in', css.match(/var\(--[a-z-]+,[^)]*\)/g) ?? []);
    report('corner radius', [...css.matchAll(/border-radius:\s*([^;}]+)/g)].map(match => match[1].trim()).filter(value => value !== '0' && !/^var\(--radius-[a-z]+\)$/.test(value)));
    // Spacing is a whole number of space units: `var(--space-unit)` or `calc(var(--space-unit) * n)`, or 0.
    const spacing = [...css.matchAll(/\{([^{}]*)\}/g)]
      .flatMap(block => [...block[1].matchAll(/(?:^|;)\s*(?:margin|padding|gap|row-gap|column-gap|inset|top|right|bottom|left)(?:-[a-z-]+)?\s*:\s*([^;]+)/g)])
      .map(match => match[1].trim());
    report('typed spacing', spacing.flatMap(value => value.match(/-?(?:\d+\.?\d*|\.\d+)(?:px|r?em)\b/g) ?? []).filter(length => Number.parseFloat(length) !== 0));
    report('spacing off the 4 px scale', spacing.flatMap(value => [...value.matchAll(/var\(--space-unit\)\s*([*/])\s*(-?[\d.]+)/g)])
      .filter(([, operator, number]) => operator === '/' || !Number.isInteger(Number(number))).map(match => match[0]));
  }
  return found;
}

export function findScreenViolations(texts = Object.fromEntries(tokenScreens.map(file => [file, read(file)]))) {
  const found = [];
  for (const [file, text] of Object.entries(texts)) {
    const where = path.relative(root, file).replaceAll('\\', '/');
    const code = text.replace(/\/\/.*$/gm, '');
    const report = (problem, values) => { for (const value of new Set(values)) found.push(`${where}: ${problem} ${value} dp`); };
    report('corner size', [...code.matchAll(/RoundedCornerShape\(\s*([\d.]+)\.dp\s*\)/g)].map(match => match[1]));
    report('target height', [...code.matchAll(/heightIn\(\s*min\s*=\s*([\d.]+)\.dp/g)].map(match => match[1]).filter(value => Number(value) <= 48));
  }
  return found;
}

export function staleOutputs(tokens) {
  const expected = { [cssFile]: renderCss(tokens), [kotlinFile]: renderKotlin(tokens) };
  return Object.entries(expected).filter(([file, text]) => !existsSync(file) || read(file) !== text);
}

// Windows terminals can report the drive letter in either case.
if (process.argv[1] && path.resolve(process.argv[1]).toLowerCase() === fileURLToPath(import.meta.url).toLowerCase()) {
  const tokens = loadTokens();
  const stale = staleOutputs(tokens);
  if (process.argv.includes('--check')) {
    const problems = [
      ...stale.map(([file]) => `${path.relative(root, file)} is out of date; run npm run tokens`),
      ...findHandCopies(tokens),
      ...findStyleViolations(),
      ...findScreenViolations(),
      ...contrastFailures(tokens),
    ];
    if (problems.length) {
      console.error(problems.join('\n'));
      process.exit(1);
    }
    console.log('Design tokens: generated files are current, no copied values, contrast pairs pass.');
  } else {
    for (const [file, text] of stale) writeFileSync(file, text);
    console.log(stale.length ? `Design tokens: wrote ${stale.map(([file]) => path.relative(root, file)).join(', ')}` : 'Design tokens: generated files already current.');
  }
}
