// Generated by scripts/design-tokens.mjs from packages/design-tokens/tokens.json. Do not edit; run npm run tokens.
package com.community.platform

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object DesignTokens {
    val Ink = Color(0xFF18362F)
    val Muted = Color(0xFF5A6E67)
    val Primary = Color(0xFF17634F)
    val PrimaryHover = Color(0xFF104F3E)
    val PrimarySurface = Color(0xFFE8F2ED)
    val Background = Color(0xFFF6F8F6)
    val Surface = Color(0xFFFFFFFF)
    val Border = Color(0xFFDCE4DF)
    val ControlBorder = Color(0xFFACBCB3)
    val Placeholder = Color(0xFF798980)
    val Accent = Color(0xFFB4553D)
    val Danger = Color(0xFFA53032)
    val LetterSpacing = 0.sp
    val SpaceUnit = 4.dp
    val ControlRadius = 6.dp
    val DialogRadius = 8.dp
    val MinimumTarget = 48.dp
}
