"""initial_identity.

Revision: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_rate_buckets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_identity_rate_buckets_expires_at'), 'identity_rate_buckets', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_lookup', sa.String(length=64), nullable=False),
    sa.Column('email_cipher', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deactivated', 'deletion_requested')", name='ck_user_status'),
    sa.CheckConstraint('version > 0', name='ck_user_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_lookup')
    )
    op.create_table('account_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_digest')
    )
    op.create_index('ix_session_account', 'account_sessions', ['account_id', 'created_at'], unique=False)
    op.create_table('domain_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_key', sa.String(length=64), nullable=False),
    sa.Column('context_digest', sa.String(length=64), nullable=False),
    sa.Column('email_lookup', sa.String(length=64), nullable=False),
    sa.Column('email_cipher', sa.Text(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('proof_digest', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose IN ('registration', 'recovery')", name='ck_challenge_purpose'),
    sa.CheckConstraint('attempts >= 0', name='ck_challenge_attempts'),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index('ix_challenge_email_purpose', 'identity_challenges', ['email_lookup', 'purpose'], unique=False)
    op.create_table('identity_security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_security_events_account_id'), 'identity_security_events', ['account_id'], unique=False)
    op.create_table('identity_mail_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payload_cipher', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['identity_challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_identity_mail_due', 'identity_mail_jobs', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identity_mail_due', table_name='identity_mail_jobs')
    op.drop_table('identity_mail_jobs')
    op.drop_index(op.f('ix_identity_security_events_account_id'), table_name='identity_security_events')
    op.drop_table('identity_security_events')
    op.drop_index('ix_challenge_email_purpose', table_name='identity_challenges')
    op.drop_table('identity_challenges')
    op.drop_table('domain_outbox')
    op.drop_index('ix_session_account', table_name='account_sessions')
    op.drop_table('account_sessions')
    op.drop_table('users')
    op.drop_index(op.f('ix_identity_rate_buckets_expires_at'), table_name='identity_rate_buckets')
    op.drop_table('identity_rate_buckets')
    # ### end Alembic commands ###